ACTION_GET_API_LIMITS = 'get_api_limits'
ACTION_GET_API_QUERY_LIMITS = 'get_api_query_limits'
ACTION_GET_API_SUBMISSION_LIMITS = 'get_api_submission_limits'
ACTION_GET_ENVIRONMENTS = 'get_environments'
ACTION_GET_FEED = 'get_feed'
ACTION_GET_NSSF_FILES = 'get_nssf_files'
ACTION_GET_NSSF_LIST = 'get_nssf_list'
ACTION_GET_RELATIONSHIPS = 'get_relationships'
ACTION_GET_RESULT = 'get_result'
ACTION_GET_SAMPLE_DROPPED_FILES = 'get_sample_dropped_files'
ACTION_GET_SAMPLE_SCREENSHOTS = 'get_sample_screenshots'
ACTION_GET_SCAN = 'get_scan'
ACTION_GET_BULK_SCAN = 'get_bulk_scan'
ACTION_GET_STATE = 'get_state'
ACTION_GET_SUMMARY = 'get_summary'
ACTION_GET_BULK_SUMMARY = 'get_bulk_summary'
ACTION_GET_SYSTEM_BACKEND = 'get_system_backend'
ACTION_GET_SYSTEM_IN_PROGRESS = 'get_system_in_progress'
ACTION_GET_SYSTEM_HEARTBEAT = 'get_system_heartbeat'
ACTION_GET_SYSTEM_STATE = 'get_system_state'
ACTION_GET_SYSTEM_STATS = 'get_system_stats'
ACTION_GET_SYSTEM_QUEUE_SIZE = 'get_system_queue_size'
ACTION_GET_URL_HASH = 'get_url_hash'
ACTION_REANALYZE_SAMPLE = 'reanalyze_sample'
ACTION_SEARCH = 'search'
# ACTION_SUBMIT_DROPPED_FILE = 'submit_dropped_file'
# ACTION_SUBMIT_FILE = 'submit_file'
ACTION_SUBMIT_URL_FILE = 'submit_url_file'
ACTION_SUBMIT_URL = 'submit_url'

ACTION_SEARCH_HASH = 'search_hash'
ACTION_SEARCH_HASHES = 'search_hashes'
ACTION_SEARCH_STATES = 'search_states'
ACTION_SEARCH_TERMS = 'search_terms'

ACTION_GET_OVERVIEW = 'overview_get'
ACTION_GET_REFRESHED_OVERVIEW = 'overview_get_refreshed'
ACTION_GET_OVERVIEW_SUMMARY = 'overview_get_summary'
ACTION_GET_OVERVIEW_SAMPLE = 'overview_download_sample'

ACTION_SUBMIT_DROPPED_FILE = 'submit_dropped_file'
ACTION_SUBMIT_FILE = 'submit_file'
ACTION_SUBMIT_HASH_FOR_URL = 'submit_hash_for_url'
ACTION_SUBMIT_REANALYZE = 'submit_reanalyze'
ACTION_SUBMIT_URL_FOR_ANALYSIS = 'submit_url_for_analysis'
ACTION_SUBMIT_URL_TO_FILE = 'submit_url_to_file'


MINIMAL_SUPPORTED_INSTANCE_VERSION = '8.10'
